export const storeData = {
  name: "Demo Fashion Store",
  platform: "Shopify",
  currency: "£",
  orders: 500,
  revenue: 24500,
  products: 25,
  customers: 380,
};

export const kpiData = {
  revenue: { value: "£24,500", growth: 12.5, trend: [30, 35, 32, 40, 38, 45, 50] },
  orders: { value: "500", growth: 8.2, trend: [20, 25, 22, 28, 30, 32, 35] },
  customers: { value: "380", growth: 15.3, trend: [15, 18, 20, 22, 25, 28, 30] },
  conversion: { value: "2.8%", growth: -0.4, trend: [40, 38, 35, 32, 30, 28, 25] },
};

export const problems = [
  {
    id: 1,
    severity: "high",
    title: "Checkout abandonment increased",
    description: "Mobile checkout conversion dropped by 24% in the last 30 days.",
    loss: "£1,840",
    lossPeriod: "/month",
    action: "Investigate",
  },
  {
    id: 2,
    severity: "medium",
    title: "Product conversion decreased",
    description: 'Summer Dress conversion dropped by 17% compared to last month.',
    loss: "£620",
    lossPeriod: "/month",
    action: "Investigate",
  },
  {
    id: 3,
    severity: "medium",
    title: "Refund rate increased",
    description: "Refunds increased by 12% this month, primarily on size-related issues.",
    loss: "£480",
    lossPeriod: "/month",
    action: "Investigate",
  },
  {
    id: 4,
    severity: "low",
    title: "Shipping cost inquiry spike",
    description: "27 customers asked about shipping costs in the last 7 days.",
    loss: "£210",
    lossPeriod: "/month",
    action: "Investigate",
  },
];

export const aiRecommendations = [
  {
    id: 1,
    title: "Add free-shipping threshold",
    description:
      "AI detected that 27 customers abandoned checkout after seeing shipping costs. Adding a free-shipping threshold of £50 could recover approximately £1,840/month.",
    impact: "+£1,840/month",
    confidence: 92,
    actions: ["Update shipping settings", "Add banner to product pages"],
  },
  {
    id: 2,
    title: "Improve mobile checkout flow",
    description:
      "Mobile checkout abandonment increased by 24%. Simplify the checkout steps and show shipping costs earlier.",
    impact: "+£1,200/month",
    confidence: 87,
    actions: ["Simplify checkout", "Show shipping earlier"],
  },
  {
    id: 3,
    title: "Launch abandoned-cart campaign",
    description:
      "18% of carts are abandoned. An automated email campaign could recover 15% of abandoned carts.",
    impact: "+£920/month",
    confidence: 78,
    actions: ["Setup email automation", "Create discount code"],
  },
];

export const revenueTrend = [
  { day: "Mon", value: 4200 },
  { day: "Tue", value: 3800 },
  { day: "Wed", value: 5100 },
  { day: "Thu", value: 4600 },
  { day: "Fri", value: 6200 },
  { day: "Sat", value: 7500 },
  { day: "Sun", value: 6800 },
];

export const revenueByChannel = [
  { name: "Direct", value: 9800, percent: 40, growth: 8.5 },
  { name: "Organic Search", value: 7350, percent: 30, growth: 12.1 },
  { name: "Social Media", value: 4900, percent: 20, growth: -2.3 },
  { name: "Email", value: 2450, percent: 10, growth: 5.7 },
];

export const topProducts = [
  {
    id: 1,
    name: "Summer Dress",
    image: null,
    units: 124,
    revenue: 4960,
    conversion: 4.2,
    growth: 12.5,
  },
  {
    id: 2,
    name: "Classic Blazer",
    image: null,
    units: 89,
    revenue: 6230,
    conversion: 3.8,
    growth: 8.1,
  },
  {
    id: 3,
    name: "Silk Blouse",
    image: null,
    units: 156,
    revenue: 5460,
    conversion: 3.5,
    growth: -1.2,
  },
  {
    id: 4,
    name: "Denim Jacket",
    image: null,
    units: 67,
    revenue: 4690,
    conversion: 2.9,
    growth: 15.3,
  },
  {
    id: 5,
    name: "Linen Pants",
    image: null,
    units: 98,
    revenue: 3430,
    conversion: 3.1,
    growth: 6.7 },
];

export const orders = [
  {
    id: "ORD-001",
    customer: "Emma Wilson",
    email: "emma@example.com",
    productCount: 2,
    total: 129.99,
    paymentStatus: "Paid",
    fulfillmentStatus: "Shipped",
    date: "2025-08-01",
    avatar: null,
  },
  {
    id: "ORD-002",
    customer: "James Smith",
    email: "james@example.com",
    productCount: 1,
    total: 79.5,
    paymentStatus: "Pending",
    fulfillmentStatus: "Processing",
    date: "2025-08-01",
    avatar: null,
  },
  {
    id: "ORD-003",
    customer: "Sophia Brown",
    email: "sophia@example.com",
    productCount: 3,
    total: 245.0,
    paymentStatus: "Paid",
    fulfillmentStatus: "Delivered",
    date: "2025-07-31",
    avatar: null,
  },
  {
    id: "ORD-004",
    customer: "Liam Johnson",
    email: "liam@example.com",
    productCount: 1,
    total: 49.99,
    paymentStatus: "Failed",
    fulfillmentStatus: "Cancelled",
    date: "2025-07-31",
    avatar: null,
  },
  {
    id: "ORD-005",
    customer: "Olivia Davis",
    email: "olivia@example.com",
    productCount: 2,
    total: 189.0,
    paymentStatus: "Paid",
    fulfillmentStatus: "Processing",
    date: "2025-07-30",
    avatar: null,
  },
  {
    id: "ORD-006",
    customer: "Noah Miller",
    email: "noah@example.com",
    productCount: 1,
    total: 59.99,
    paymentStatus: "Refunded",
    fulfillmentStatus: "Cancelled",
    date: "2025-07-30",
    avatar: null,
  },
  {
    id: "ORD-007",
    customer: "Ava Wilson",
    email: "ava@example.com",
    productCount: 4,
    total: 320.0,
    paymentStatus: "Paid",
    fulfillmentStatus: "Shipped",
    date: "2025-07-29",
    avatar: null,
  },
  {
    id: "ORD-008",
    customer: "William Brown",
    email: "william@example.com",
    productCount: 1,
    total: 39.99,
    paymentStatus: "Paid",
    fulfillmentStatus: "Delivered",
    date: "2025-07-29",
    avatar: null,
  },
];

export const orderStatuses = [
  { name: "Pending", count: 12, color: "warning" },
  { name: "Processing", count: 8, color: "info" },
  { name: "Shipped", count: 24, color: "primary" },
  { name: "Delivered", count: 45, color: "success" },
  { name: "Cancelled", count: 6, color: "danger" },
  { name: "Refunded", count: 5, color: "muted" },
];

export const customers = [
  {
    id: 1,
    name: "Emma Wilson",
    email: "emma@example.com",
    totalOrders: 12,
    totalSpent: 1240.5,
    lastOrder: "2025-08-01",
    status: "Active",
    avatar: null,
  },
  {
    id: 2,
    name: "James Smith",
    email: "james@example.com",
    totalOrders: 5,
    totalSpent: 420.0,
    lastOrder: "2025-07-28",
    status: "Active",
    avatar: null,
  },
  {
    id: 3,
    name: "Sophia Brown",
    email: "sophia@example.com",
    totalOrders: 8,
    totalSpent: 890.75,
    lastOrder: "2025-07-25",
    status: "Active",
    avatar: null,
  },
  {
    id: 4,
    name: "Liam Johnson",
    email: "liam@example.com",
    totalOrders: 2,
    totalSpent: 150.0,
    lastOrder: "2025-07-15",
    status: "Inactive",
    avatar: null,
  },
  {
    id: 5,
    name: "Olivia Davis",
    email: "olivia@example.com",
    totalOrders: 15,
    totalSpent: 2100.0,
    lastOrder: "2025-08-01",
    status: "VIP",
    avatar: null,
  },
];

export const revenueLeaks = [
  {
    id: 1,
    severity: "high",
    title: "Checkout Abandonment",
    description: "28% increase in checkout abandonment on mobile devices.",
    loss: "£1,840",
    lossPeriod: "/month",
  },
  {
    id: 2,
    severity: "medium",
    title: "Refund Loss",
    description: "12% increase in refunds, primarily size-related returns.",
    loss: "£480",
    lossPeriod: "/month",
  },
  {
    id: 3,
    severity: "low",
    title: "Discount Overuse",
    description: "Overuse of discount codes reducing average order value.",
    loss: "£210",
    lossPeriod: "/month",
  },
  {
    id: 4,
    severity: "medium",
    title: "Inventory Stockouts",
    description: "3 popular products frequently out of stock.",
    loss: "£620",
    lossPeriod: "/month",
  },
  {
    id: 5,
    severity: "low",
    title: "Failed Payments",
    description: "2.3% payment failure rate on mobile checkout.",
    loss: "£340",
    lossPeriod: "/month",
  },
];

export const orderAlerts = [
  {
    id: 1,
    priority: "high",
    title: "High-value order pending",
    description: "Order ORD-007 worth £320 has been pending for 3 hours.",
    impact: "Potential fulfillment delay",
  },
  {
    id: 2,
    priority: "high",
    title: "Payment failed",
    description: "3 payments failed in the last hour due to gateway issues.",
    impact: "£340 potential loss",
  },
  {
    id: 3,
    priority: "medium",
    title: "Shipping delayed",
    description: "5 orders delayed due to carrier issues.",
    impact: "Customer satisfaction risk",
  },
  {
    id: 4,
    priority: "medium",
    title: "Refund requested",
    description: "2 refund requests pending approval.",
    impact: "£180 potential refund",
  },
  {
    id: 5,
    priority: "low",
    title: "Inventory unavailable",
    description: "Summer Dress is out of stock in size M.",
    impact: "Lost sales opportunity",
  },
];

export const activities = [
  { id: 1, title: "Revenue increased after campaign", time: "2 hours ago", type: "success" },
  { id: 2, title: "Refund spike detected", time: "5 hours ago", type: "warning" },
  { id: 3, title: "High-value customer purchase", time: "1 day ago", type: "success" },
  { id: 4, title: "New revenue opportunity identified", time: "2 days ago", type: "info" },
  { id: 5, title: "Checkout abandonment increased", time: "3 days ago", type: "danger" },
];
